### ISSUE TITLE
Autoreloading procedurally gets faster

### ISSUE THREAD

**Issue by SenchoPoro42** [Hetag1216/AreaReloader#5]
I've configured different times for all areas, after my last issue. But I've noticed the reason I stopped trying to use this plugin last I tried a few weeks ago.

After it has been running for a while, it starts resetting every 20 seconds. No errors, no extra information in debug.
MC 1.15.2, Tuinity Java v11
Worldedit 7.1.0

**Comment by SenchoPoro42** [comment]
Now every 10 seconds...

**Comment by Hetag1216** [comment]
Hi again;
After setting the time have you restarted the server?

**Comment by SenchoPoro42** [comment]
I mererely reloaded through the built-in commands, have been contemplating a restart, but that will become bothersome during adjustment of timings. Will try it now though.

**Comment by SenchoPoro42** [comment]
A restart does seem to have fixed it, annoying that it speeds up more and more if you don't do it once.

**Comment by Hetag1216** [comment]
Glad to see that the issue was fixed.
If you'd ever encounter any further issues feel free to open a new issue in this tab and i'll get to you as soon as possible!
