### ISSUE TITLE
AutoReloading notifications always on

### ISSUE THREAD

**Issue by SenchoPoro42** [Hetag1216/AreaReloader#6]
Been having an issue for a while now where despite NotifyWhenReloading = false it still posts in console every time. Debug is false as well.
I don't know how your plugin posts into the console since I can't prevent it from posting in the console with ChatControlPro or ConsoleSpamFix.

![image](https://user-images.githubusercontent.com/60812656/83426960-474f8280-a430-11ea-8f07-78ffcced5921.png)

**Comment by Hetag1216** [comment]
Hello,
the notify on reload setting only works for the ops who are online on the server.
It still sends the messages to the console for a safety purpose, even if the setting is set to false.
However, in the next AR version there will be an option to disable console from getting notified whenever an area reloads, as well with some new features.
Right now I cannot give you further help in stopping the messages, I ask you to have patient until the new build is released.

**Comment by Hetag1216** [comment]
Issue fixed ca37094 - version 1.8
